# syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

COPY *.go ./
COPY Makefile ./

RUN go build -o bin/main
RUN go test -v ./...

EXPOSE 8080

CMD [ "/app/bin/main" ]
