# syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

COPY *.go ./
COPY Makefile ./

RUN make
RUN make test

EXPOSE 8080

CMD [ "/bin/app" ]
